fix(arvie): various variables naming

diff --git a/arvie b/arvie
--- a/arvie
+++ b/arvie
@@ -4,9 +4,10 @@ set -euo pipefail
 
 COMMAND=$(basename "${0}")
 
-ARVIEPATH=$(dirname "${0}")
+ARVIE_PATH=$(dirname "${0}")
 
 DBGCMD="echo   ----> "
+# DBGCMD=""
 
 usage() {
   echo >&2 "Arvie runs Arvados with docker-compose https://github.com/netmanagers/arvie"
@@ -18,18 +19,20 @@ usage() {
   echo >&2 "      -h, --help            Display this help and exit"
   echo >&2
   echo >&2 "Environment variables:"
-  echo >&2 "  * ARVIE_ENV:              Arvie's env dir to use as part of various dirs to create"
+  echo >&2 "  * ARVIE_CLUSTER_ENV:      Arvie's env dir to use as part of various dirs to create"
   echo >&2 "                            Defaults to 'arvie'"
-  echo >&2 "                            Current value '${ARVIE_ENV}'"
-  echo >&2 "  * ARVIE_CLUSTER:          A unique 5 letters word to use as the Arvados' cluster name"
+  echo >&2 "                            Current value '${ARVIE_CLUSTER_ENV}'"
+  echo >&2 "  * ARVIE_CLUSTER_NAME:     A unique 5 letters word to use as the Arvados' cluster name"
   echo >&2 "                            Defaults to 'arvie'"
-  echo >&2 "                            Current value '${ARVIE_CLUSTER}'"
-  echo >&2 "  * ARVIE_DATA:             Directory where arvie's data will be persisted"
-  echo >&2 "                            Defaults to '${HOME}/.local/arvie/arvie'"
-  echo >&2 "                            Current value '${HOME}/.local/arvie/${ARVIE_ENV}'"
-  echo >&2 "  * ARVIE_CONFIG:           Directory where arvie's config is stored"
+  echo >&2 "                            Current value '${ARVIE_CLUSTER_NAME}'"
+  echo >&2 "  * ARVIE_DATA_DIR:         Base directory where arvie clusters' data will be persisted"
+  echo >&2 "                            Defaults to '${HOME}/.local/arvie'"
+  echo >&2 "                            Current value '${ARVIE_DATA_DIR}'"
+  echo >&2 "                            Current cluster's ('${ARVIE_CLUSTER_NAME}') data will be stored at '${ARVIE_DATA}'"
+  echo >&2 "  * ARVIE_CONFIG_DIR:       Directory where arvie clusters' config are stored"
   echo >&2 "                            Defaults to '${HOME}/.config/arvie/arvie'"
-  echo >&2 "                            Current value '${HOME}/.config/arvie/${ARVIE_ENV}'"
+  echo >&2 "                            Current value '${ARVIE_CONFIG_DIR}'"
+  echo >&2 "                            Current cluster's ('${ARVIE_CLUSTER_NAME}') config will be stored at '${ARVIE_CONFIG}'"
   echo >&2
   echo >&2 "Commands and options:"
   echo >&2
@@ -50,7 +53,7 @@ usage() {
   echo >&2
   echo >&2 "    create options:"
   echo >&2 "      -n, --name            A unique 5 letters word to use as the Arvados' cluster name"
-  echo >&2 "                            Defaults to \$ARVIE_CLUSTER (current value: ${ARVIE_CLUSTER})"
+  echo >&2 "                            Defaults to \$ARVIE_CLUSTER (current value: ${ARVIE_CLUSTER_NAME})"
   echo >&2 "      -s, --scaffold        One of the templates from the 'scaffold' dir"
   echo >&2 "                              which will be used to create the new cluster config"
   echo >&2 "                            Defaults to 'template1'"
@@ -70,7 +73,7 @@ usage() {
   echo >&2
   echo >&2 "    clean options:"
   echo >&2 "      -a, --all             Deletes all locally persisted data from"
-  echo >&2 "                            HOST_DATA_DIR (current value '${HOME}/.local/arvie/${ARVIE_ENV}/data')"
+  echo >&2 "                            HOST_DATA_DIR (current value '${HOME}/.local/arvie/${ARVIE_CLUSTER_ENV}/data')"
   echo >&2 "      -c, --cache           Deletes the gem/pip/npm cache completely"
   echo >&2 "                            WARNING!!!! This will impact in all your existing clusters, as the cache"
   echo >&2 "                              directory is common to all running Arvie clusters"
@@ -86,19 +89,14 @@ usage() {
   echo >&2
 }
 
-# Set some defaults, based on whether some ENV vars are set
-### ENVIRONMENT DIR TO USE
-[ -z "${ARVIE_ENV:-}" ] && ARVIE_ENV=arvie
-### CLUSTER NAME TO USE
-[ -z "${ARVIE_CLUSTER:-}" ] && ARVIE_CLUSTER=arvie
-
+# SET SOME DEFAULTS, BASED ON WHETHER SOME ENV VARS ARE SET
 # These are based on the XDG standard
 # https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
 ### BASE DIR TO PERSIST DATA
-[ -z "${ARVIE_DATA:-}" ] && ARVIE_DATA="${HOME}/.local/arvie/${ARVIE_ENV}"
+[ -z "${ARVIE_DATA_DIR:-}" ] && ARVIE_DATA_DIR="${HOME}/.local/arvie"
 
 ### BASE DIR TO PERSIST CONFIGS
-[ -z "${ARVIE_CONFIG:-}" ] && ARVIE_CONFIG="${HOME}/.config/arvie/${ARVIE_ENV}"
+[ -z "${ARVIE_CONFIG_DIR:-}" ] && ARVIE_CONFIG_DIR="${HOME}/.config/arvie"
 
 TAG="latest"
 IMAGES_TO_BUILD=""
@@ -109,15 +107,24 @@ SED=""
 SCAFFOLD="template1"
 DOMAIN="arv.local"
 
+### Environment dir for this cluster
+[ -z "${ARVIE_CLUSTER_ENV:-}" ] && ARVIE_CLUSTER_ENV="arvie"
+### This cluster's name
+[ -z "${ARVIE_CLUSTER_NAME:-}" ] && ARVIE_CLUSTER_NAME="arvie"
+
+# This cluster's data dir
+ARVIE_DATA="${ARVIE_DATA_DIR}/${ARVIE_CLUSTER_ENV}"
+ARVIE_CONFIG="${ARVIE_CONFIG_DIR}/${ARVIE_CLUSTER_ENV}"
+
 # FIXME
 # getip() {
-#   docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $ARVIE_ENV
+#   docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $ARVIE_CLUSTER_ENV
 # }
 # getclusterid() {
-#   docker exec $ARVIE_ENV cat $ARVADOS_CLUSTER_PATH/api_uuid_prefix
+#   docker exec $ARVIE_CLUSTER_ENV cat $ARVADOS_CLUSTER_PATH/api_uuid_prefix
 # }
 # listusers() {
-#   docker exec -ti $ARVIE_ENV /usr/local/lib/arvie/edit_users.py $ARVADOS_CLUSTER_PATH/cluster_config.yml $(getclusterid) list
+#   docker exec -ti $ARVIE_CLUSTER_ENV /usr/local/lib/arvie/edit_users.py $ARVADOS_CLUSTER_PATH/cluster_config.yml $(getclusterid) list
 # }
 # wait_for_arvie() { }
 # running_config() { }
@@ -151,7 +158,7 @@ arguments() {
         shift 2
         ;;
       -n | --name)
-        ARVIE_CLUSTER=${2}
+        ARVIE_CLUSTER_NAME=${2}
         shift 2
         ;;
       -s | --scaffold)
@@ -201,10 +208,10 @@ build() {
   BUILD_TAG="${TAG}"
 EOF
 
-  echo "Building ${ARVIE_ENV}/${ARVIE_CLUSTER} Arvados' images"
+  echo "Building ${ARVIE_CLUSTER_ENV}/${ARVIE_CLUSTER_NAME} Arvados' images"
   ${DBGCMD} COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 BUILD_TAG="${TAG}" docker-compose \
-    --env-file ${ARVIE_ENV}/compose/compose.env \
-    --file ${ARVIE_ENV}/compose/build.yml \
+    --env-file ${ARVIE_CLUSTER_ENV}/compose/compose.env \
+    --file ${ARVIE_CLUSTER_ENV}/compose/build.yml \
     --log-level DEBUG \
     build ${IMAGES_TO_BUILD}
 }
@@ -213,7 +220,7 @@ EOF
 load_compose_env() {
   if [ ! -d "${ARVIE_CONFIG}" ]; then
     echo >&2
-    echo >&2 "${ARVIE_ENV} environment dirs for cluster ${ARVIE_CLUSTER} are missing."
+    echo >&2 "${ARVIE_CLUSTER_ENV} environment dirs for cluster ${ARVIE_CLUSTER_NAME} are missing."
     echo >&2
     echo >&2 "Please create them with"
     echo >&2 "  ${COMMAND} env"
@@ -230,11 +237,11 @@ load_compose_env() {
 
 prepare_arvie_env() {
   # FIXME! We should remove this and let the user say where is the Arvados code
-  if [ -f "${ARVIEPATH}/arvados/CODE_OF_CONDUCT.md" ]; then
+  if [ -f "${ARVIE_PATH}/arvados/CODE_OF_CONDUCT.md" ]; then
     echo >&2 "Arvados repository already exists. Skipping"
   else
-    echo >&2 "Downloading Arvados into the '${ARVIEPATH}/arvados/' subdir"
-    cd "${ARVIEPATH}"
+    echo >&2 "Downloading Arvados into the '${ARVIE_PATH}/arvados/' subdir"
+    cd "${ARVIE_PATH}"
     ${DBGCMD} git submodule update --init
     ${DBGCMD} git submodule update --checkout
     cd -
@@ -249,14 +256,14 @@ prepare_arvie_env() {
 
     echo >&2 "Building the NPM, Ruby gems and Golang caches"
     ${DBGCMD} COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose \
-      --env-file "${ARVIE_ENV}/compose/compose.env" \
-      --file "${ARVIE_ENV}/cache.yml" \
+      --env-file "${ARVIE_CLUSTER_ENV}/compose/compose.env" \
+      --file "${ARVIE_CLUSTER_ENV}/cache.yml" \
       up --remove-orphans gem-cache
 
     echo >&2 "Tearing down the images used to build the cache"
     ${DBGCMD} docker-compose \
-      --env-file "${ARVIE_ENV}/compose/compose.env" \
-      --file "${ARVIE_ENV}/cache.yml" down
+      --env-file "${ARVIE_CLUSTER_ENV}/compose/compose.env" \
+      --file "${ARVIE_CLUSTER_ENV}/cache.yml" down
   fi
 }
 
@@ -266,21 +273,24 @@ create_env() {
   else
     # Add the final replacement strings
     [ "x${SED}" != "x" ] && SED="${SED};"
-    SED="${SED} s/__CLUSTER__/${ARVIE_CLUSTER}/g; s/__DOMAIN__/${DOMAIN}/g"
+    SED="${SED} s/__CLUSTER__/${ARVIE_CLUSTER_NAME}/g; s/__DOMAIN__/${DOMAIN}/g"
     echo "SED LINE: $SED"
 
     # Do the job
     echo "Cloning template ${SCAFFOLD} to ${ARVIE_CONFIG}"
     ${DBGCMD} mkdir -pv "${ARVIE_CONFIG}"
     ${DBGCMD} mkdir -pv "${ARVIE_DATA}"
-    ${DBGCMD} cp -r "${ARVIEPATH}/scaffold/${SCAFFOLD}" "${ARVIE_CONFIG}"
+    ${DBGCMD} cp -r "${ARVIE_PATH}/scaffold/${SCAFFOLD}" "${ARVIE_CONFIG}"
 
-    echo "Replacing vars in ${ARVIE_ENV}"
+    echo "Replacing vars in ${ARVIE_CLUSTER_ENV}"
     ${DBGCMD} find "${ARVIE_CONFIG}" -type f -exec sed -i "${SED}" {} \;
   fi
+}
 
+# FIXME! Remove this and make postgresql work without SSL?
+create_postgresql_ssl_cert() {
   if [ -f "${HOST_CONF_DIR}/ssl/server.key" ]; then
-    echo "The snakeoil cert already exists for cluster ${ARVIE_CLUSTER}. Skipping"
+    echo "The snakeoil cert already exists for cluster ${ARVIE_CLUSTER_NAME}. Skipping"
   else
     echo "Generating SSL certs for Postgresql and nginx under ${HOST_CONF_DIR}/ssl"
     mkdir -p "${HOST_CONF_DIR}/ssl"
@@ -340,7 +350,7 @@ compose() {
 # Parse the arguments
 arguments ${@}
 
-if [ ${#ARVIE_CLUSTER} -ne 5 ]; then
+if [ ${#ARVIE_CLUSTER_NAME} -ne 5 ]; then
   echo >&2 "ERROR: <ARVIE_CLUSTER> must be exactly 5 characters long"
   echo >&2 "Run './${COMMAND} --help' to get the valid parameters and variables"
   exit 1
@@ -361,6 +371,7 @@ case "${subcmd}" in
     ;;
   compose)
     load_compose_env
+    create_postgresql_ssl_cert
     COMMAND_LINE=${@}
     ${DBGCMD} compose ${COMMAND_LINE}
     ;;
@@ -373,6 +384,7 @@ case "${subcmd}" in
     ;;
   up)
     load_compose_env
+    create_postgresql_ssl_cert
     COMMAND_LINE=${@}
     ${DBGCMD} compose ${COMMAND_LINE} up
     ;;
