refactor(environments): add the possibility to create multiple clusters
* added the env command, to create a new cluster/env, cloning from a scaffold
* add all commands the requirement to specify an environment
* validate that the environment exists before running commands
* change some default vars in the scaffold, to deploy to .local/arvie (XDG standards)

diff --git a/arvie b/arvie
--- a/arvie
+++ b/arvie
@@ -11,19 +11,17 @@ set -euo pipefail
 
 usage() {
   echo >&2
-  echo >&2 "Usage: $0 [-h|--help] [command] [options]"
+  echo >&2 "Usage: $0 [-h|--help] <CLUSTER> <command> [options]"
   echo >&2
   echo >&2 "$0 parameters:"
   echo >&2 "  -h, --help: Display this help and exit"
+  echo >&2 "  <CLUSTER> the cluster on which [command] will be applied"
   echo >&2 "  command: One of"
     echo >&2 "          up"
     echo >&2 "          down"
-  for c in ${AVAILABLE_COMMANDS}; do 
+  for c in ${AVAILABLE_COMMANDS}; do
     echo >&2 "          $c"
   done
-  echo >&2 "    You can use the command 'compose' to pass verbatim instructions"
-  echo >&2 "    to 'docker-compose', with the yaml files used to run Arvados"
-  echo >&2 ""
   echo >&2 "    To get help for an specific command, run"
   echo >&2 "    $0 <command> [-h|--help]"
   echo >&2 ""
@@ -31,18 +29,38 @@ usage() {
 
 AVAILABLE_COMMANDS=$(ls commands | grep -v README.rst)
 
-if [ $# -eq 0 -o "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" ]; then
+# For less than 2 parameters (cluster, command), we show usage and exit
+if [ "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" -o $# -lt 2 ]; then
   usage
   exit 1
 fi
 
-COMMAND_LINE=$@
-
-if [ "x${1}" = "xup" -o "x${1}" = "xdown" ]; then
-  # We need the caches and certs in place to start the service
-  ./commands/prepare
-  COMMAND_LINE="compose $@"
+# First parameter must be the cluster. The rest, the command and parameters
+if [ ${#1} -ne 5 ]; then
+  echo "ERROR: <CLUSTER> must be exactly 5 characters long"
+  usage
+  exit 1
 fi
+CLUSTER=${1}
+shift
+COMMAND=${1}
+shift
+PARAMETERS=$@
 
-echo "Running: ${COMMAND_LINE}"
+# Prepare the line to pass to the commands
+case "x${COMMAND}" in
+  "xup")
+    # We need the caches and certs in place to start the service
+    ./commands/prepare ${CLUSTER}
+    COMMAND_LINE="compose ${CLUSTER} ${COMMAND} ${PARAMETERS}"
+    ;;
+  "xdown")
+    COMMAND_LINE="compose ${CLUSTER} ${COMMAND} ${PARAMETERS}"
+    ;;
+  *)
+    COMMAND_LINE="${COMMAND} ${CLUSTER} ${PARAMETERS}"
+    ;;
+esac
+
+echo "Running: ${COMMAND} ${PARAMETERS} on cluster ${CLUSTER}"
 ./commands/${COMMAND_LINE}
diff --git a/commands/build b/commands/build
--- a/commands/build
+++ b/commands/build
@@ -8,7 +8,9 @@ usage() {
   echo >&2
   echo >&2 "Builds local images of Arvados' components, from the Arvados subdir"
   echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help] [-t|--tag TAG] [component1] [component2] ..."
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help] [-t|--tag TAG] [component1] [component2] ..."
+  echo >&2
+  echo >&2 "  <CLUSTER> the cluster on which [${COMMAND}] will be applied"
   echo >&2
   echo >&2 "${COMMAND} options:"
   echo >&2 "  -c, --cache           Rebuild the gem/pip/npm cache before building any image"
@@ -52,6 +54,8 @@ arguments() {
     esac
   done
 
+  CLUSTER=${1}
+  shift
   IMAGES_TO_BUILD=$@
 }
 
@@ -61,14 +65,25 @@ CACHE="no"
 
 arguments $@
 
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
+
 # We use the docker-compose's .env file to configure arvie
-source .env
+source ${CLUSTER}/${CLUSTER}.env
 
 if [ "${CACHE}" = "yes" -o ! -d ${HOST_CACHE_DIR} ]; then
   source commands/prepare
 fi
 
 # Get the commit and branch to add them to the /BUILD_INFO file
+# so we know which commit/branch we're building from
 cd ${ARVADOS_ROOT}
 BUILD_COMMIT=$(git rev-parse --short HEAD)
 BUILD_BRANCH=$(git rev-parse --abbrev-ref HEAD)
@@ -80,8 +95,9 @@ BUILD_COMMIT="${BUILD_COMMIT}"
 BUILD_TAG="${TAG}"
 EOF
 
-echo "Building local Arvados' images"
+echo "Building ${CLUSTER} Arvados' images"
 COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 BUILD_TAG="${TAG}" docker-compose \
-  --file docker-compose/build.yml \
+  --env-file ${CLUSTER}/${CLUSTER}.env \
+  --file ${CLUSTER}/build.yml \
   --log-level DEBUG build \
   ${IMAGES_TO_BUILD}
diff --git a/commands/clean b/commands/clean
--- a/commands/clean
+++ b/commands/clean
@@ -8,7 +8,9 @@ usage() {
   echo >&2
   echo >&2 "Deletes lingering Arvados files or all data ,if desired"
   echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help] [-a|--all]"
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help] [-a|--all]"
+  echo >&2
+  echo >&2 "  <CLUSTER> the cluster on which [${COMMAND}] will be applied"
   echo >&2
   echo >&2 "${COMMAND} options:"
   echo >&2 "  -h, --help            Display this help and exit"
@@ -22,19 +24,32 @@ if [ "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" ]; then
   exit 0
 fi
 
-source .env
+CLUSTER=${1}
+
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
+
+# We use the docker-compose's .env file to configure arvie
+source ${CLUSTER}/${CLUSTER}.env
 
 # Clean stuff lingering around so we can reset everything
 cd ${ARVADOS_ROOT} || exit 1
 
-echo "FIXME! Removing PID files"
-sudo rm -vf apps/workbench/tmp/pids/server.pid services/api/tmp/pids/server.pid
+echo "FIXME! Removing PID files. This is an issue with multiple clusters!!!!"
+echo sudo rm -vf apps/workbench/tmp/pids/server.pid services/api/tmp/pids/server.pid
 
-echo "FIXME! resetting db files, modified by api on startup"
-git checkout -- apps/workbench/db/schema.rb services/api/db/structure.sql
+echo "FIXME! resetting db files, modified by api on startup. This is an issue with multiple clusters!!!!"
+echo git checkout -- apps/workbench/db/schema.rb services/api/db/structure.sql
 cd ${BASE_DIR}
 
 if [ "x${1:-}" = "x-a" -o "x${1:-}" = "x--all" ]; then
   echo "Removing all locally persisted data"
-  sudo rm -rvf ${HOST_CACHE_DIR} ${HOST_DATA_DIR}
+  echo sudo rm -rvf ${HOST_CACHE_DIR} ${HOST_DATA_DIR}
 fi
diff --git a/commands/compose b/commands/compose
--- a/commands/compose
+++ b/commands/compose
@@ -6,9 +6,11 @@ COMMAND=$(basename $0)
 
 usage() {
   echo >&2
-  echo >&2 "Passes the arguments it receives to 'docker-compose'"
+  echo >&2 "Passes the arguments it receives verbatim to 'docker-compose'"
   echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help] [arguments to docker compose]" 
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help] [arguments to docker compose]" 
+  echo >&2
+  echo >&2 "  <CLUSTER> the cluster on which [${COMMAND}] will be applied"
   echo >&2
   echo >&2 "${COMMAND} options:"
   echo >&2 "  -h, --help            Display this help and exit"
@@ -45,6 +47,8 @@ arguments() {
     esac
   done
 
+  CLUSTER=${1}
+  shift
   COMMAND_LINE=$@
 }
 
@@ -53,8 +57,20 @@ COMMAND_LINE=""
 
 arguments $@
 
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
+
 # We use the docker-compose's .env file to configure arvie
-source .env
+source ${CLUSTER}/${CLUSTER}.env
 
 echo "Running docker-compose"
-BUILD_TAG=${TAG} docker-compose --file docker-compose/base.yml --log-level DEBUG ${COMMAND_LINE}
+BUILD_TAG=${TAG} docker-compose \
+  --file ${CLUSTER}/base.yml \
+  --log-level DEBUG ${COMMAND_LINE}
diff --git a/commands/env b/commands/env
--- a/commands/env
+++ b/commands/env
@@ -8,11 +8,13 @@ usage() {
   echo >&2
   echo >&2 "Prepares and manages Arvie environments to run clusters"
   echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help]" 
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help]" 
+  echo >&2
+  echo >&2 "  <CLUSTER> the cluster on which [${COMMAND}] will be applied"
   echo >&2
   echo >&2 "           -h, --help            Display this help and exit"
   echo >&2
-  echo >&2 "       arvie ${COMMAND} create [-t|--template TEMPLATE] [-v|--var VAR1=value] [-v|--var VAR2=value2] [-v|--var VARN=valueN] <CLUSTER> [DOMAIN]" 
+  echo >&2 "       arvie <CLUSTER> ${COMMAND} create [-t|--template TEMPLATE] [-v|--var VAR1=value] [-v|--var VAR2=value2] [-v|--var VARN=valueN] [DOMAIN]" 
   echo >&2
   echo >&2 "         create options:"
   echo >&2 "           -t, --template        One of the templates from the 'scaffold' dir"
@@ -91,6 +93,16 @@ DOMAIN="arv.local"
 
 arguments $@
 set_required_params ${COMMAND_LINE}
+
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
 
 # Add the final replacement strings
 [ "x${SED}" != "x" ] && SED="${SED};"
diff --git a/commands/prepare b/commands/prepare
--- a/commands/prepare
+++ b/commands/prepare
@@ -12,7 +12,9 @@ usage() {
   echo >&2 "If all requirements are already fulfilled, it will do nothing."
   echo >&2 "Otherwise, will create any of the missing ones."
   echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help]"
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help]>"
+  echo >&2
+  echo >&2 "  <CLUSTER> the cluster environment that will be prepared"
   echo >&2
 }
 
@@ -21,21 +23,34 @@ if [ "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" ]; then
   exit 0
 fi
 
-# We use the docker-compose's .env file to configure arvie
-source .env
+CLUSTER=${1}
 
-if [ -f configs/ssl/server.key ]; then
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
+
+# We use the cluster's docker-compose .env file to configure arvie
+source ${CLUSTER}/${CLUSTER}.env
+
+if [ -f ${HOST_CONF_DIR}/ssl/server.key ]; then
   echo "The snakeoil cert already exists. Skiping"
 else
   echo "Generating SSL certs for Postgresql (and nginx for now)"
-  mkdir -p configs/ssl
-  openssl req -new -text -passout pass:abcd -subj /CN=localhost -out configs/ssl/server.req -keyout configs/ssl/privkey.pem
-  openssl rsa -in configs/ssl/privkey.pem -passin pass:abcd -out configs/ssl/server.key
-  openssl req -x509 -in configs/ssl/server.req -text -key configs/ssl/server.key -out configs/ssl/server.crt
-  chmod 600 configs/ssl/server.key
-  test $(uname -s) == Linux && sudo chown 70 configs/ssl/server.key
+  mkdir -p ${HOST_CONF_DIR}/ssl
+  openssl req -new -text -passout pass:abcd -subj /CN=localhost -out ${HOST_CONF_DIR}/ssl/server.req -keyout ${HOST_CONF_DIR}/ssl/privkey.pem
+  openssl rsa -in ${HOST_CONF_DIR}/ssl/privkey.pem -passin pass:abcd -out ${HOST_CONF_DIR}/ssl/server.key
+  openssl req -x509 -in ${HOST_CONF_DIR}/ssl/server.req -text -key ${HOST_CONF_DIR}/ssl/server.key -out ${HOST_CONF_DIR}/ssl/server.crt
+  chmod 600 ${HOST_CONF_DIR}/ssl/server.key
+  test $(uname -s) == Linux && sudo chown 70 ${HOST_CONF_DIR}/ssl/server.key
 fi
 
+# FIXME! We should remove this and let the user say where is the Arvados code
 if [ -f arvados/CODE_OF_CONDUCT.md ]; then
   echo "Arvados repository already exists. Skiping"
 else
@@ -51,9 +66,13 @@ else
   mkdir -p ${HOST_GEMCACHE} ${HOST_GOCACHE} ${HOST_PIPCACHE} ${HOST_NPMCACHE}
 
   echo "Building the NPM, Ruby gems and Golang caches"
-  COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose --file docker-compose/cache.yml up --remove-orphans gem-cache
+  COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose \
+    --env-file ${CLUSTER}/${CLUSTER}.env \
+    --file ${CLUSTER}/cache.yml \
+    up --remove-orphans gem-cache
+
   echo "Tearing down the images used to build the cache"
-  docker-compose --file docker-compose/cache.yml down
+  docker-compose --file ${CLUSTER}/cache.yml down
 fi
 
-echo "arvie environment is ready"
+echo "${CLUSTER} environment is ready"
diff --git a/commands/trace b/commands/trace
--- a/commands/trace
+++ b/commands/trace
@@ -9,9 +9,7 @@ usage() {
   echo >&2 "Starts Arvados with Opentracing+Jaeger"
   echo >&2 "It passes the commands verbatim to docker-compose, so start it with"
   echo >&2
-  echo >&2 "    arvie ${COMMAND} up"
-  echo >&2
-  echo >&2 "Usage: arvie ${COMMAND} [-h|--help] [arguments to docker compose]" 
+  echo >&2 "Usage: arvie <CLUSTER> ${COMMAND} [-h|--help] [arguments to docker compose]" 
   echo >&2
   echo >&2 "${COMMAND} options:"
   echo >&2 "  -h, --help            Display this help and exit"
@@ -24,10 +22,21 @@ if [ "x${1:-}" = "x-h" -o "x${1:-}" = "x--help" ]; then
   exit 0
 fi
 
+CLUSTER=${1}
+
+# Check if the cluster already exists
+if [ ! -d ${CLUSTER} ]; then
+  echo >&2 "ERROR: cluster ${CLUSTER} does not yet exist."
+  echo >&2
+  echo >&2 "       Please, create the cluster environment first, with the command"
+  echo >&2
+  echo >&2 "       arvie <CLUSTER> env"
+  exit 1
+fi
+
 # We use the docker-compose's .env file to configure arvie
-source .env
+source ${CLUSTER}/${CLUSTER}.env
 
 echo "Running docker-compose"
-docker-compose --file docker-compose/base.yml \
-               --file docker-compose/trace.yml \
+docker-compose --file ${CLUSTER}/trace.yml \
                --log-level DEBUG $@
